spring.application.name=review-platform

server.port=8080
server.servlet.context-path=/review-platform
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=${DB_USERNAME:C##REVIEW_APP}
spring.datasource.password=ReviewApp@1234

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=MYDB4PM
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
tinyfish.api-key=sk-tinyfish-pAJmKDWy9X1G5HYz_vGRu4TBFkxMGsxx

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}

spring.mail.username=sahilkolhe49@gmail.com
spring.mail.password=xvxn knzx efri qoai

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=${APP_BASE_URL:http://localhost:8080/review-platform}
spring.thymeleaf.prefix=/
spring.thymeleaf.check-template-location=false

spring.web.resources.chain.enabled=false